/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    FolderTree: typeof import('./src/components/FolderTree.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
  }
}
