/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTree: typeof import('element-plus/es')['ElTree']
    FolderTree: typeof import('./src/components/FolderTree.vue')['default']
    IXterm: typeof import('./src/components/IXterm.vue')['default']
    JKSLibButton: typeof import('./src/components/JKSLibButton.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    RemoteTreeFile: typeof import('./src/components/RemoteTreeFile.vue')['default']
    RightContentMenu: typeof import('./src/components/vs-tree/components/RightContentMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerminalComponent: typeof import('./src/components/TerminalComponent.vue')['default']
    VsCodeSlider: typeof import('./src/components/vs-tree/VsCodeSlider.vue')['default']
  }
}
